### ISSUE TITLE
Club detail activity

### ISSUE THREAD

**Issue by aqelkp** [The-WebOps-Club/instieventsapp#14]
- Change the background color to the same color as of MainActivity
- Put a black overlay above the image and display the name in it
- Load logo using glide and put a gen image if no image is available
  @skiranjyothi  We have done this in ERP 
  Check https://github.com/The-WebOps-Club/ERPAndroid/blob/master/app/src/main/res/layout/alert_profile_dialog.xml for layout

**Comment by skiranjyothi** [comment]
Acknowledged
